#!/bin/bash

#ssh不绑定接口
uci -q delete dropbear.@dropbear[0].Interface
uci commit dropbear

#修改主题
uci -q set luci.main.mediaurlbase=/luci-static/argon
uci commit luci

#修改默认系统设置
#修改时区
uci -q set system.@system[0].timezone='CST-8'
uci -q set system.@system[0].zonename='Asia/Shanghai'
#删除默认ntp服务器
uci -q delete system.ntp.server
#增加ntp服务器
uci -q add_list system.ntp.server=ntp.ntsc.ac.cn
uci -q add_list system.ntp.server=ntp.aliyun.com
uci -q add_list system.ntp.server=cn.ntp.org.cn
uci commit system

#网络设置
#修改wan口配置
uci -q set network.wan.device='eth0'
uci -q set network.wan6.device='eth0'
#uci -q set network.wan.proto='static'
#uci -q set network.wan.ipaddr='192.168.1.2'
#uci -q set network.wan.gateway='192.168.1.1'
#uci -q set network.wan.netmask='255.255.255.0'
#uci -q set network.wan.dns='223.5.5.5 114.114.114.114'
#修改lan口配置
uci -q delete network.lan.ipaddr
uci -q add_list network.lan.ipaddr='192.168.2.1/24'
uci -q delete network.@device[0].ports
uci -q add_list network.@device[0].ports='eth1'
uci -q add_list network.@device[0].ports='eth2'
uci -q add_list network.@device[0].ports='eth3'
uci -q add_list network.@device[0].ports='eth4'
uci -q add_list network.@device[0].ports='eth5'
uci commit network

#修改防火墙，允许WAN口入栈和转发
#uci -q set firewall.@defaults[0].output='ACCEPT'
#uci -q set firewall.@defaults[0].input='ACCEPT'
#uci -q set firewall.@defaults[0].forward='ACCEPT'
#uci -q set firewall.@zone[1].output='ACCEPT'
#uci -q set firewall.@zone[1].input='ACCEPT'
#uci -q set firewall.@zone[1].forward='ACCEPT'
#uci commit firewall

#ttyd网页终端允许wan口访问以及设置端口
#uci -q delete ttyd.@ttyd[0].interface
uci set ttyd.@ttyd[0].port='7681'
uci set ttyd.@ttyd[0].url_override='/ttyd'
uci commit ttyd

#openclash允许wan口连接代理端口及设置管理页面端口
#uci -q set openclash.config.intranet_allowed='0'
uci -q set openclash.config.cn_port='9090'
uci -q set openclash.config.dashboard_forward_port='9090'
uci commit openclash

#NPS内网穿透服务
uci -q set npc.@npc[0].enable='0'
uci -q set npc.@npc[0].server_addr=''
uci -q set npc.@npc[0].protocol='tcp'
uci -q set npc.@npc[0].vkey=''
uci -q set npc.@npc[0].dns=''
uci commit npc
