name: Remove old artifacts

on:
  schedule:
    # Every day at 1am
    - cron: '0 1 * * *'
  repository_dispatch:

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    # For private repos
    permissions:
      actions: write

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          # '<number> <unit>', e.g. 5 days, 2 years, 90 seconds, parsed by Moment.js
          age: '30 days'
          # Optional inputs
          # skip-tags: true
          # skip-recent: 5
